//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "meet")]
# [serde (rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub user_id: Option<i64>,
    pub dept_id: Option<i64>,
    pub title: Option<String>,
    pub location: Option<i64>,
    pub duration: Option<String>,
    pub detail: Option<String>,
    pub startdt: Option<DateTime>,
    pub enddt: Option<DateTime>,
    pub online_url: Option<String>,
    pub meet_num: Option<String>,
    pub background_color: Option<String>,
    pub create_by: Option<String>,
    pub create_time: Option<DateTime>,
    pub update_by: Option<String>,
    pub update_time: Option<DateTime>,
    pub asignee_id: Option<i64>,
    pub asignee_name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
