//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod gen_table;
pub mod gen_table_column;
pub mod meet;
pub mod meetroom;
pub mod qrtz_blob_triggers;
pub mod qrtz_calendars;
pub mod qrtz_cron_triggers;
pub mod qrtz_fired_triggers;
pub mod qrtz_job_details;
pub mod qrtz_locks;
pub mod qrtz_paused_trigger_grps;
pub mod qrtz_scheduler_state;
pub mod qrtz_simple_triggers;
pub mod qrtz_simprop_triggers;
pub mod qrtz_triggers;
pub mod sys_config;
pub mod sys_dept;
pub mod sys_dict_data;
pub mod sys_dict_type;
pub mod sys_job;
pub mod sys_job_log;
pub mod sys_logininfor;
pub mod sys_menu;
pub mod sys_notice;
pub mod sys_oper_log;
pub mod sys_post;
pub mod sys_role;
pub mod sys_role_dept;
pub mod sys_role_menu;
pub mod sys_user;
pub mod sys_user_post;
pub mod sys_user_role;
