//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "qrtz_blob_triggers")]
# [serde (rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub sched_name: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub trigger_name: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub trigger_group: String,
    #[sea_orm(column_type = "Binary(255)", nullable)]
    pub blob_data: Option<Vec<u8>>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::qrtz_triggers::Entity",
        from = "(Column::SchedName, Column::TriggerName, Column::TriggerGroup)",
        to = "(super::qrtz_triggers::Column::SchedName, super::qrtz_triggers::Column::TriggerName, super::qrtz_triggers::Column::TriggerGroup)",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    QrtzTriggers,
}

impl Related<super::qrtz_triggers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QrtzTriggers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
