//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "qrtz_triggers")]
# [serde (rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub sched_name: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub trigger_name: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub trigger_group: String,
    pub job_name: String,
    pub job_group: String,
    pub description: Option<String>,
    pub next_fire_time: Option<i64>,
    pub prev_fire_time: Option<i64>,
    pub priority: Option<i32>,
    pub trigger_state: String,
    pub trigger_type: String,
    pub start_time: i64,
    pub end_time: Option<i64>,
    pub calendar_name: Option<String>,
    pub misfire_instr: Option<i16>,
    #[sea_orm(column_type = "Binary(255)", nullable)]
    pub job_data: Option<Vec<u8>>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::qrtz_blob_triggers::Entity")]
    QrtzBlobTriggers,
    #[sea_orm(has_one = "super::qrtz_cron_triggers::Entity")]
    QrtzCronTriggers,
    #[sea_orm(
        belongs_to = "super::qrtz_job_details::Entity",
        from = "(Column::SchedName, Column::JobName, Column::JobGroup)",
        to = "(super::qrtz_job_details::Column::SchedName, super::qrtz_job_details::Column::JobName, super::qrtz_job_details::Column::JobGroup)",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    QrtzJobDetails,
    #[sea_orm(has_one = "super::qrtz_simple_triggers::Entity")]
    QrtzSimpleTriggers,
    #[sea_orm(has_one = "super::qrtz_simprop_triggers::Entity")]
    QrtzSimpropTriggers,
}

impl Related<super::qrtz_blob_triggers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QrtzBlobTriggers.def()
    }
}

impl Related<super::qrtz_cron_triggers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QrtzCronTriggers.def()
    }
}

impl Related<super::qrtz_job_details::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QrtzJobDetails.def()
    }
}

impl Related<super::qrtz_simple_triggers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QrtzSimpleTriggers.def()
    }
}

impl Related<super::qrtz_simprop_triggers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QrtzSimpropTriggers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
