//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "qrtz_fired_triggers")]
# [serde (rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub sched_name: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub entry_id: String,
    pub trigger_name: String,
    pub trigger_group: String,
    pub instance_name: String,
    pub fired_time: i64,
    pub sched_time: i64,
    pub priority: i32,
    pub state: String,
    pub job_name: Option<String>,
    pub job_group: Option<String>,
    pub is_nonconcurrent: Option<String>,
    pub requests_recovery: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
