//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "qrtz_job_details")]
# [serde (rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub sched_name: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub job_name: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub job_group: String,
    pub description: Option<String>,
    pub job_class_name: String,
    pub is_durable: String,
    pub is_nonconcurrent: String,
    pub is_update_data: String,
    pub requests_recovery: String,
    #[sea_orm(column_type = "Binary(255)", nullable)]
    pub job_data: Option<Vec<u8>>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::qrtz_triggers::Entity")]
    QrtzTriggers,
}

impl Related<super::qrtz_triggers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QrtzTriggers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
